apiVersion: v1
kind: Pod
metadata:
  name: httpbin-pod
  namespace: mynamespacefdbf2b
  labels:
    app: httpbin
  annotations:
    azure.workload.identity/inject-proxy-sidecar: "true"
    azure.workload.identity/proxy-sidecar-port: "8000"
spec:
  serviceAccountName: myserviceaccountfdbf2b
  containers:
  - name: httpbin
    image: docker.io/kennethreitz/httpbin
    env:
    - name: IDENTITY_ENDPOINT
      value: "http://localhost:8000/metadata/identity/oauth2/token"
    - name: IDENTITY_HEADER
      value: "true"
    - name: IMDS_ENDPOINT
      value: "http://169.254.169.254"
