apiVersion: v1
kind: Service
metadata:
  name: tensorflow-service
  namespace: tensorflow-cluster
spec:
  selector:
    app: tensorflow
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
  type: LoadBalancer
