apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow-deployment
  namespace: tensorflow-cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tensorflow
  template:
    metadata:
      labels:
        app: tensorflow
    spec:
      containers:
      - name: tensorflow-container
        image: tensorflow/tensorflow:latest
        ports:
        - containerPort: 8501
